kanban/urls.py
from django.urls import path
from .views import *

app_name = 'kanban'

urlpatterns = [
	path('', index, name='index'),
	path('create/task', create_task, name='create_task'),
	path('create/project', create_project, name='create_project'),
	path('project/<int:project_id>', view_project, name='view_project'),
	path('task/<int:task_id>', change_status, name='change_status'),
	path('project/<int:project_id>/task/user/<int:user_id>', user_tasks, name='user_tasks'),
	path('project/<int:project_id>/task/executor/<int:user_id>', task_executor, name='task_executor'),
	path('task/<int:task_id>/executor/add', add_executor, name='add_executor'),
	path('/project/<int:project_id>/task/<int:task_id>/stage-of-execution/set', set_stage_of_execution, name='set_stage_of_execution'),
	path('project/<int:project_id>/task/<int:task_id>/add-discussion', add_discussion, name='add_discussion')
]

kanban_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('users.urls')),
	path('', include('kanban.urls'))
]

users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
	path('login', login, name='login'),
	path('register', register, name='register'),
	path('logout', logout, name='logout')
]

kanban/models.py
from django.db import models
from django.contrib.auth.models import User


class TaskStatus(models.Model):
	title = models.CharField('Статус', max_length=200)

	def __str__(self):
		return self.title


class Project(models.Model):
	title = models.CharField('Название', max_length=500)

	def __str__(self):
		return self.title


class StageOfExecution(models.Model):
	title = models.CharField('Название', max_length=200)

	def __str__(self):
		return self.title
	

class Discussion(models.Model):
	data = models.DateTimeField('Дата обсуждения')

	def __str__(self):
		return f'Обсуждение {self.data}'


class Task(models.Model):
	title = models.CharField("Название", max_length=500)
	description = models.TextField("Описание")
	status = models.ForeignKey(TaskStatus, on_delete=models.PROTECT)
	project = models.ForeignKey(Project, on_delete=models.CASCADE)
	executors = models.ManyToManyField(User, related_name='executors', null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.PROTECT)
	stage_of_execution = models.ForeignKey(StageOfExecution, on_delete=models.PROTECT, null=True, blank=True)
	discussion = models.ForeignKey(Discussion, null=True, blank=True, on_delete=models.SET_NULL)

	def __str__(self):
		return self.title

kanban/forms.py
from django import forms
from .models import TaskStatus, Task, Project, StageOfExecution, Discussion


class ChangeTaskStatusForm(forms.Form):
	status = forms.ModelChoiceField(queryset=TaskStatus.objects.all(), empty_label="Поменять статус задачи", widget=forms.Select(attrs={'class': 'task-status', 'id': 'select'}))


class ChangeTaskStageOfExecutionForm(forms.Form):
	stage_of_execution = forms.ModelChoiceField(queryset=StageOfExecution.objects.all(), empty_label="Выбрать этап выполнения", widget=forms.Select(attrs={'class':'task-status', 'id':'select'}))


class TaskCreationForm(forms.ModelForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите название'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-input resize-vertical', 'placeholder': 'Введите описание'}))
	status = forms.ModelChoiceField(queryset=TaskStatus.objects.all(), widget=forms.Select(attrs={'class': 'form-input'}), empty_label='Выберите статус')
	project = forms.ModelChoiceField(queryset=Project.objects.all(), widget=forms.Select(attrs={'class': 'form-input'}), empty_label='Выберите проект')
	class Meta:
		model = Task
		fields = ['title', 'description', 'status', 'project']


class ProjectCreationForm(forms.ModelForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите название проекта'}))
	class Meta:
		model = Project
		fields = ['title']


class DiscussionCreationForm(forms.ModelForm):
	data = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'form-input', 'type': 'datetime-local'}))
	class Meta:
		model = Discussion
		fields = ['data']

kanban/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from .models import Project, Task, StageOfExecution, TaskStatus
from .forms import ChangeTaskStatusForm, TaskCreationForm, ProjectCreationForm, ChangeTaskStageOfExecutionForm, DiscussionCreationForm


# Create your views here.
@login_required
def index(request):
	projects = Project.objects.all()
	return render(request, 'kanban/index.html', {'projects': projects})


@login_required
def view_project(request, project_id):
	tasks = Task.objects.filter(project__id=project_id)
	project = Project.objects.get(id=project_id)
	status_form = ChangeTaskStatusForm()
	stage_form = ChangeTaskStageOfExecutionForm()
	return render(request, 'kanban/project_view.html', {'tasks': tasks, 'status_form': status_form, 'stage_form': stage_form, 'project': project})


@login_required
def change_status(request, task_id):
	if request.method == 'POST':
		form = ChangeTaskStatusForm(data=request.POST)
		if form.is_valid():
			task = Task.objects.get(id=task_id)
			task.status = form.cleaned_data.get('status')
			if task.stage_of_execution.title == 'Выполнено':
				stage_of_execution = StageOfExecution.objects.get(title='Ожидание')
				task.stage_of_execution = stage_of_execution
			task.save()
			return redirect(request.META.get('HTTP_REFERER'))


@login_required
def create_task(request):
	if request.method == 'POST':
		form = TaskCreationForm(data=request.POST)
		form.instance.user = request.user
		if form.is_valid():
			form.save()
			return redirect(request.META.get('HTTP_REFERER'))
	else:
		form = TaskCreationForm()
	return render(request, 'kanban/create_task.html', {'form': form})


@login_required
def user_tasks(request, project_id, user_id):
	tasks = Task.objects.filter(user__id=user_id, project__id=project_id)
	project = Project.objects.get(id=project_id)
	form = ChangeTaskStatusForm()
	return render(request, 'kanban/project_view.html', {'tasks': tasks, 'form': form, 'project': project})


@login_required
def create_project(request):
	if request.method == 'POST':
		form = ProjectCreationForm(data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('kanban:index')
	else:
		form = ProjectCreationForm()
	return render(request, 'kanban/create_project.html', {'form': form})


@login_required
def task_executor(request, project_id, user_id):
	tasks = Task.objects.filter(executors__id=user_id, project__id=project_id)
	project = Project.objects.get(id=project_id)
	form = ChangeTaskStatusForm()
	return render(request, 'kanban/project_view.html', {'form': form, 'tasks': tasks, 'project': project})


@login_required
def add_executor(request, task_id):
	task = Task.objects.get(id=task_id)
	stage_of_execution = StageOfExecution.objects.get(title='Выполняется')
	task.executors.add(request.user)
	task.stage_of_execution = stage_of_execution
	task.save()
	return redirect(request.META.get('HTTP_REFERER'))


@login_required
def set_stage_of_execution(request, project_id, task_id):
	if request.method == 'POST':
		form = ChangeTaskStageOfExecutionForm(data=request.POST)
		if form.is_valid():
			if form.cleaned_data.get('stage_of_execution').title == 'Обсуждается':
				return redirect('kanban:add_discussion', project_id, task_id)
			else:
				task = Task.objects.get(id=task_id)
				if task.discussion:
					task.stage_of_execution = form.cleaned_data.get('stage_of_execution')
					task.save()
					task.discussion.delete()
				elif form.cleaned_data.get('stage_of_execution').title == 'Выполнено':
					task.stage_of_execution = form.cleaned_data.get('stage_of_execution')
					status = TaskStatus.objects.get(title='Завершена')
					task.status = status
					task.save()
				else:
					if task.status.title == 'Завершена':
						status = TaskStatus.objects.get(title='Срочно, важно')
						task.status = status
					task.stage_of_execution = form.cleaned_data.get('stage_of_execution')
					task.save()
				return redirect(request.META.get('HTTP_REFERER'))
		

@login_required
def add_discussion(request, project_id, task_id):
	if request.method == 'POST':
		form = DiscussionCreationForm(data=request.POST)
		if form.is_valid():
			task = Task.objects.get(id=task_id)
			if task.status.title == 'Завершена':
				status = TaskStatus.objects.get(title='Срочно, важно')
				task.status = status
			stage_of_execution = StageOfExecution.objects.get(title='Обсуждается')
			discussion = form.save()
			task.discussion = discussion
			task.stage_of_execution = stage_of_execution
			task.save()
			return redirect('kanban:view_project', project_id)
		
	project = Project.objects.get(id=project_id)
	form = DiscussionCreationForm()
	return render(request, 'kanban/add_discussion.html', {'project': project, 'form': form, 'project_id': project_id, 'task_id': task_id})

templates/kanban/add_discussion.html
{% extends 'kanban/layouts/main.html' %}
{% load static %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/create_form.css' %}">
{% endblock %}
{% block content %}
	<div class="main">
		<form action="{% url 'kanban:add_discussion' project_id task_id %}" method="post" class="form">
			<h1>Добавить обсуждение</h1>
			{% csrf_token %}
			{{ form.data }}
			<button class='form-button' type="submit">Добавить</button>
		</form>
	</div>
{% endblock %}

templates/kanban/create_project.html
{% extends 'kanban/layouts/main.html' %}
{% load static %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/create_form.css' %}">
{% endblock %}
{% block content %}
	<div class="main">
		<form action="{% url 'kanban:create_project' %}" method="post" class="form">
			<h1>Создание проекта</h1>
			{% csrf_token %}
			{{ form.title }}
			<button type="submit" class='form-button'>Создать</button>
		</form>
	</div>
{% endblock %}

templates/kanban/create_task.html
{% extends 'kanban/layouts/main.html' %}
{% load static %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/create_form.css' %}">
{% endblock %}
{% block content %}
	<div class="main">
		<form action="{% url 'kanban:create_task' %}" method="post" class="form">
			<h1>Создание заявки</h1>
			{% csrf_token %}
			{{ form.title }}
			{{ form.description }}
			{{ form.project }}
			{{ form.status }}
			<button type="submit" class='form-button'>Создать</button>
		</form>
	</div>
{% endblock %}

templates/kanban/index.html
{% extends 'kanban/layouts/main.html'%}
{% load static %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}
{% block content %}
	<div class="main">
		{% for project in projects %}
			<a href="{% url 'kanban:view_project' project.id %}" class="card">
				<h2>{{ project.title }}</h2>
			</a>
		{% endfor %}
	</div>
{% endblock %}

templates/kanban/project_view.html
{% extends 'kanban/layouts/main.html' %}
{% load static %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/project_view.css' %}">
{% endblock %}
{% block content %}
	<div class="main">
		<div class="task-column">
			<div class="column-header gray">
				Не срочно, не важно
			</div>
			{% for task in tasks %}
				{% if task.status.id == 1 %}
					<div class="task">
						<div class="task-header">
							<h2>{{ task.title }}</h2>
							{% if task.stage_of_execution %}
								<div class="chip">{{ task.stage_of_execution.title }}</div>
							{% endif %}
						</div>
						{% if task.discussion %}
							<span>Обсждается: {{ task.discussion.data }}</span>
						{% endif %}
						{% if request.user in task.executors.all %}
							<div class='task-forms'>
								<form action="{% url 'kanban:change_status' task.id %}" method='post' class='task-form'>
									{% csrf_token %}
									{{ status_form.status }}
								</form>
								<form action="{% url 'kanban:set_stage_of_execution' task.project.id task.id %}" method="post" class="task-form">
									{% csrf_token %}
									{{ stage_form.stage_of_execution }}
								</form>
							</div>
						{% else %}
							<a href="{% url 'kanban:add_executor' task.id %}" class='btn success'>Принять</a>
						{% endif %}
						<div>
							{{ task.description }}
						</div>
						<div class='task-creator'>
							<span>Создано:</span>
							<a href="{% url 'kanban:user_tasks' task.project.id task.user.id %}" class='task-user'>{{ task.user.username }}</a>
						</div>
						<div class='task-executors'>
							<span>Исполнитель:</span>
							{% for executor in task.executors.all %}
								<a href="{% url 'kanban:task_executor' task.project.id executor.id %}" class="task-user">{{ executor.username }}</a>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<div class="task-column">
			<div class="column-header alert">
				Cрочно, не важно
			</div>
			{% for task in tasks %}
				{% if task.status.id == 2 %}
					<div class="task">
						<div class="task-header">
							<h2>{{ task.title }}</h2>
							{% if task.stage_of_execution %}
								<div class="chip">{{ task.stage_of_execution.title }}</div>
							{% endif %}
						</div>
						{% if task.discussion %}
							<span>Обсждается: {{ task.discussion.data }}</span>
						{% endif %}
						{% if request.user in task.executors.all %}
							<div class='task-forms'>
								<form action="{% url 'kanban:change_status' task.id %}" method='post' class='task-form'>
									{% csrf_token %}
									{{ status_form.status }}
								</form>
								<form action="{% url 'kanban:set_stage_of_execution' task.project.id task.id %}" method="post" class="task-form">
									{% csrf_token %}
									{{ stage_form.stage_of_execution }}
								</form>
							</div>
						{% else %}
							<a href="{% url 'kanban:add_executor' task.id %}" class='btn success'>Принять</a>
						{% endif %}
						<div>
							{{ task.description }}
						</div>
						<div class='task-creator'>
							<span>Создано:</span>
							<a href="{% url 'kanban:user_tasks' task.project.id task.user.id %}" class='task-user'>{{ task.user.username }}</a>
						</div>
						<div class='task-executors'>
							<span>Исполнитель:</span>
							{% for executor in task.executors.all %}
								<a href="{% url 'kanban:task_executor' task.project.id executor.id %}" class="task-user">{{ executor.username }}</a>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<div class="task-column">
			<div class="column-header warrning">
				Не срочно, важно
			</div>
			{% for task in tasks %}
				{% if task.status.id == 3 %}
					<div class="task">
						<div class="task-header">
							<h2>{{ task.title }}</h2>
							{% if task.stage_of_execution %}
								<div class="chip">{{ task.stage_of_execution.title }}</div>
							{% endif %}
						</div>
						{% if task.discussion %}
							<span>Обсждается: {{ task.discussion.data }}</span>
						{% endif %}
						{% if request.user in task.executors.all %}
							<div class='task-forms'>
								<form action="{% url 'kanban:change_status' task.id %}" method='post' class='task-form'>
									{% csrf_token %}
									{{ status_form.status }}
								</form>
								<form action="{% url 'kanban:set_stage_of_execution' task.project.id task.id %}" method="post" class="task-form">
									{% csrf_token %}
									{{ stage_form.stage_of_execution }}
								</form>
							</div>
						{% else %}
							<a href="{% url 'kanban:add_executor' task.id %}" class='btn success'>Принять</a>
						{% endif %}
						<div>
							{{ task.description }}
						</div>
						<div class='task-creator'>
							<span>Создано:</span>
							<a href="{% url 'kanban:user_tasks' task.project.id task.user.id %}" class='task-user'>{{ task.user.username }}</a>
						</div>
						<div class='task-executors'>
							<span>Исполнитель:</span>
							{% for executor in task.executors.all %}
								<a href="{% url 'kanban:task_executor' task.project.id executor.id %}" class="task-user">{{ executor.username }}</a>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<div class="task-column">
			<div class="column-header danger">
				Срочно, важно
			</div>
			{% for task in tasks %}
				{% if task.status.id == 4 %}
					<div class="task">
						<div class="task-header">
							<h2>{{ task.title }}</h2>
							{% if task.stage_of_execution %}
								<div class="chip">{{ task.stage_of_execution.title }}</div>
							{% endif %}
						</div>
						{% if task.discussion %}
							<span>Обсждается: {{ task.discussion.data }}</span>
						{% endif %}
						{% if request.user in task.executors.all %}
							<div class='task-forms'>
								<form action="{% url 'kanban:change_status' task.id %}" method='post' class='task-form'>
									{% csrf_token %}
									{{ status_form.status }}
								</form>
								<form action="{% url 'kanban:set_stage_of_execution' task.project.id task.id %}" method="post" class="task-form">
									{% csrf_token %}
									{{ stage_form.stage_of_execution }}
								</form>
							</div>
						{% else %}
							<a href="{% url 'kanban:add_executor' task.id %}" class='btn success'>Принять</a>
						{% endif %}
						<div>
							{{ task.description }}
						</div>
						<div class='task-creator'>
							<span>Создано:</span>
							<a href="{% url 'kanban:user_tasks' task.project.id task.user.id %}" class='task-user'>{{ task.user.username }}</a>
						</div>
						<div class='task-executors'>
							<span>Исполнитель:</span>
							{% for executor in task.executors.all %}
								<a href="{% url 'kanban:task_executor' task.project.id executor.id %}" class="task-user">{{ executor.username }}</a>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<div class="task-column">
			<div class="column-header success">
				Завершено
			</div>
			{% for task in tasks %}
				{% if task.status.id == 5 %}
					<div class="task">
						<div class="task-header">
							<h2>{{ task.title }}</h2>
							{% if task.stage_of_execution %}
								<div class="chip">{{ task.stage_of_execution.title }}</div>
							{% endif %}
						</div>
						{% if task.discussion %}
							<span>Обсждается: {{ task.discussion.data }}</span>
						{% endif %}
						{% if request.user in task.executors.all %}
							<div class='task-forms'>
								<form action="{% url 'kanban:change_status' task.id %}" method='post' class='task-form'>
									{% csrf_token %}
									{{ status_form.status }}
								</form>
								<form action="{% url 'kanban:set_stage_of_execution' task.project.id task.id %}" method="post" class="task-form">
									{% csrf_token %}
									{{ stage_form.stage_of_execution }}
								</form>
							</div>
						{% else %}
							<a href="{% url 'kanban:add_executor' task.id %}" class='btn success'>Принять</a>
						{% endif %}
						<div>
							{{ task.description }}
						</div>
						<div class='task-creator'>
							<span>Создано:</span>
							<a href="{% url 'kanban:user_tasks' task.project.id task.user.id %}" class='task-user'>{{ task.user.username }}</a>
						</div>
						<div class='task-executors'>
							<span>Исполнитель:</span>
							{% for executor in task.executors.all %}
								<a href="{% url 'kanban:task_executor' task.project.id executor.id %}" class="task-user">{{ executor.username }}</a>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
	<script src="{% static 'js/auto_form_submit.js' %}"></script>
{% endblock %}